server:
  servlet:
    context-path: /filmslibrary-api
  port: 8070

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movies
    username: director
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
